# Generated by Django 5.2.7 on 2025-11-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='steps',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
